#!/usr/bin/env bash

# Project Guardian - Centralized Logging Engine
#
# Purpose:
#   Provide a consistent mechanism for formatting and writing log
#   messages generated by Project Guardian scripts.
#
# Responsibilities:
#   - Validate the requested log level.
#   - Format log entries consistently.
#   - Write valid log messages to the appropriate destination.
#
# Non-responsibilities:
#   - Decide when an event should be logged.
#   - Decide the severity of an event.
#
# Public interface:
#   log_message LEVEL MESSAGE
#
# Supported levels:
#   INFO
#   WARNING
#   ERROR


# -----------------------------------------------------------------------------
# Public functions
# -----------------------------------------------------------------------------

log_message() {
    local level="$1"
    local message="$2"

    case "$level" in
        INFO|WARNING|ERROR)
            ;;
        *)
            printf 'LOGGER_ERROR: Unsupported log level: %s\n' "$level" >&2
            return 2
            ;;
    esac

    printf '[%s] [%s] %s\n' \
        "$(date '+%Y-%m-%d %H:%M:%S')" \
        "$level" \
        "$message"

    return 0
}
