version: "3.8"

services:
  pihole:
    container_name: guardian-pihole
    image: ${PIHOLE_IMAGE}
    hostname: guardian-pihole

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"

    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      FTLCONF_dns_listeningMode: "ALL"

    volumes:
      - ./etc-pihole:/etc/pihole

    restart: unless-stopped
